version: '3.8'

services:
  app:
    image: ${DOCKERHUB_USERNAME}/team-b-25-1-be:latest
    container_name: odg-backend
    restart: always
    env_file:
      - ./.env

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app